"""
Export Service - Generate consulting briefings and exports.
"""

import os
from datetime import datetime
from typing import List, Optional
from core.settings import settings
from core.models import Citation
import redis
import json

# Redis client for session storage
redis_client = redis.from_url(settings.redis_url)


class ExportService:
    """Service for exporting chat conversations and generating briefings."""
    
    @staticmethod
    def get_session_messages(session_id: str) -> List[dict]:
        """Retrieve all messages from a session."""
        try:
            messages_json = redis_client.get(f"session:{session_id}:messages")
            if messages_json:
                return json.loads(messages_json)
            return []
        except Exception as e:
            print(f"Failed to get session messages: {e}")
            return []
    
    @staticmethod
    def format_citations(citations: List[Citation]) -> str:
        """Format citations as markdown."""
        if not citations:
            return ""
        
        md = "\n\n---\n\n## References\n\n"
        for i, citation in enumerate(citations, 1):
            md += f"{i}. **{citation.document_name}**"
            if citation.page_number:
                md += f" (Page {citation.page_number})"
            md += f"\n   - Relevance Score: {citation.score:.3f}\n"
            md += f"   - *{citation.text[:200]}...*\n\n"
        return md
    
    @staticmethod
    def generate_briefing_markdown(
        project_id: str,
        session_id: str,
        template: str = "brief",
        project_name: Optional[str] = None
    ) -> str:
        """Generate a consulting briefing in markdown format."""
        
        # Get messages from session
        messages = ExportService.get_session_messages(session_id)
        
        # Build briefing header
        project_name = project_name or project_id
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        md = f"""# Consulting Briefing: {project_name}

**Generated:** {timestamp}  
**Template:** {template.replace('_', ' ').title()}  
**Session ID:** {session_id}

---

"""
        
        # Add executive summary section
        md += "## Executive Summary\n\n"
        md += "This briefing was generated from an AI-powered analysis using Strategic Scope RAG.\n\n"
        
        # Add conversation section
        md += "## Analysis & Discussion\n\n"
        
        if not messages:
            md += "*No conversation data available.*\n"
        else:
            for msg in messages:
                role = msg.get("role", "unknown")
                content = msg.get("content", "")
                citations = msg.get("citations", [])
                
                if role == "user":
                    md += f"### Question\n\n{content}\n\n"
                elif role == "assistant":
                    md += f"### Response\n\n{content}\n"
                    
                    # Add citations if available
                    if citations:
                        citation_objs = [Citation(**c) for c in citations]
                        md += ExportService.format_citations(citation_objs)
                    
                    md += "\n"
        
        # Add footer
        md += "\n---\n\n"
        md += f"*Generated by Strategic Scope RAG - {timestamp}*\n"
        md += "*This document contains AI-generated content and should be reviewed by subject matter experts.*\n"
        
        return md
    
    @staticmethod
    def generate_swot_markdown(
        project_id: str,
        session_id: str,
        project_name: Optional[str] = None
    ) -> str:
        """Generate a SWOT analysis briefing."""
        
        messages = ExportService.get_session_messages(session_id)
        project_name = project_name or project_id
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        md = f"""# SWOT Analysis: {project_name}

**Generated:** {timestamp}  
**Session ID:** {session_id}

---

## Strengths

"""
        
        # Extract content from messages
        for msg in messages:
            if msg.get("role") == "assistant":
                content = msg.get("content", "")
                if "strength" in content.lower() or "advantage" in content.lower():
                    md += f"{content}\n\n"
        
        md += "## Weaknesses\n\n"
        md += "## Opportunities\n\n"
        md += "## Threats\n\n"
        
        md += "\n---\n\n"
        md += f"*Generated by Strategic Scope RAG - {timestamp}*\n"
        
        return md
    
    @staticmethod
    def export_to_file(
        project_id: str,
        session_id: str,
        template: str = "brief",
        project_name: Optional[str] = None
    ) -> str:
        """Export briefing to a markdown file and return the file path."""
        
        # Generate markdown content
        if template == "swot":
            content = ExportService.generate_swot_markdown(project_id, session_id, project_name)
        else:
            content = ExportService.generate_briefing_markdown(
                project_id, session_id, template, project_name
            )
        
        # Create exports directory if it doesn't exist
        exports_dir = os.path.join(settings.data_dir, "exports")
        os.makedirs(exports_dir, exist_ok=True)
        
        # Generate filename
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"briefing_{project_id}_{template}_{timestamp}.md"
        filepath = os.path.join(exports_dir, filename)
        
        # Write to file
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)
        
        return filepath


# Initialize service instance
export_service = ExportService()

